// Default content for system (transactional) email templates. Used both to
// seed the EmailTemplate collection on server startup (if a type doesn't
// exist yet) AND to power "Reset to Default" in the admin UI.
const SUPPORT_SENDER = 'BYND Official <support@byndofficial.in>';
const ORDERS_SENDER = 'BYND Orders <orders@byndofficial.in>';

const SYSTEM_EMAIL_DEFAULTS = [
  {
    type: 'welcome',
    statusKey: null,
    label: 'Welcome Email',
    description: 'Sent right after a new account is created.',
    sender: SUPPORT_SENDER,
    subject: 'Welcome to BYND Official, {firstName}!',
    title: 'Welcome to the Family 🖤',
    message:
      'Hey {firstName} {lastName}, welcome to BYND Official! We\u2019re thrilled to have you with us. Explore the latest drops and find your next favorite piece.',
    buttonText: 'Start Shopping',
    buttonLink: '/products',
    footerText: '',
  },
  {
    type: 'order_confirmed',
    statusKey: 'confirmed',
    label: 'Order Confirmed',
    description: "Sent when an order's status changes to Confirmed.",
    sender: ORDERS_SENDER,
    subject: 'Your order #{orderId} is confirmed',
    title: '🎉 Order Confirmed!',
    message: 'Thanks for your order! Here\u2019s what you ordered:\n{productDetails}\n\nTotal: {totalAmount}',
    buttonText: 'View Order',
    buttonLink: '/orders/{orderId}',
    footerText: '',
  },
  {
    type: 'order_shipped',
    statusKey: 'shipped',
    label: 'Order Shipped',
    description: "Sent when an order's status changes to Shipped.",
    sender: ORDERS_SENDER,
    subject: 'Your order #{orderId} has shipped',
    title: '📦 Order Shipped!',
    message: 'Your order is on its way!\n{productDetails}\n\nTotal: {totalAmount}\n\nTrack it here: {trackingUrl}',
    buttonText: 'Track Order',
    buttonLink: '/orders/{orderId}',
    footerText: '',
  },
  {
    type: 'order_out_for_delivery',
    statusKey: 'out-for-delivery',
    label: 'Out for Delivery',
    description: "Sent when an order's status changes to Out for Delivery.",
    sender: ORDERS_SENDER,
    subject: 'Your order #{orderId} is out for delivery',
    title: '🚚 Out for Delivery!',
    message: 'Your order will arrive soon!\n{productDetails}\n\nTotal: {totalAmount}',
    buttonText: 'View Order',
    buttonLink: '/orders/{orderId}',
    footerText: '',
  },
  {
    type: 'order_delivered',
    statusKey: 'delivered',
    label: 'Order Delivered',
    description: "Sent when an order's status changes to Delivered.",
    sender: ORDERS_SENDER,
    subject: 'Your order #{orderId} has been delivered',
    title: '✅ Order Delivered!',
    message: 'Your order has been delivered. We hope you love it!\n{productDetails}\n\nTotal: {totalAmount}',
    buttonText: 'View Order',
    buttonLink: '/orders/{orderId}',
    footerText: '',
  },
  {
    type: 'order_cancelled',
    statusKey: 'cancelled',
    label: 'Order Cancelled',
    description: "Sent when an order's status changes to Cancelled.",
    sender: ORDERS_SENDER,
    subject: 'Your order #{orderId} has been cancelled',
    title: 'Order Cancelled',
    message: 'Your order #{orderId} has been cancelled.\n{productDetails}\n\nTotal: {totalAmount}\n\n{refundMessage}',
    buttonText: 'View Order',
    buttonLink: '/orders/{orderId}',
    footerText: '',
  },
  {
    type: 'refunded',
    statusKey: null,
    label: 'Refund Processed',
    description: 'Sent when a return/replacement request is refunded.',
    sender: ORDERS_SENDER,
    subject: 'Refund processed for order #{orderId}',
    title: 'Refund Processed',
    message: 'Your refund for order #{orderId} has been processed.\n{productDetails}',
    buttonText: 'View Order',
    buttonLink: '/orders/{orderId}',
    footerText: '',
  },
  {
    type: 'replaced',
    statusKey: null,
    label: 'Item Replaced',
    description: 'Sent when a return/replacement request results in a replacement shipment.',
    sender: ORDERS_SENDER,
    subject: 'A replacement is on its way for order #{orderId}',
    title: 'Replacement Shipped',
    message: 'A replacement for your order #{orderId} is on its way.\n{productDetails}',
    buttonText: 'View Order',
    buttonLink: '/orders/{orderId}',
    footerText: '',
  },
  {
    // Previously hardcoded in the admin frontend as a non-editable
    // reference card. Now a real, editable system template like the rest —
    // sent from controllers/user.controller.js's deleteAccount.
    type: 'account_deletion',
    statusKey: null,
    label: 'Account Deletion',
    description: 'Sent when a customer permanently deletes their own account.',
    sender: SUPPORT_SENDER,
    subject: 'Goodbye for Now',
    title: 'Goodbye for Now',
    message:
      "We're sad to see you go \ud83d\udc94\nAs requested, your BYND account has been permanently deleted.\nYou're always welcome back, and we'd love to have you again whenever you feel like returning. Until then, we wish you the very best.\nHope to see you again soon.",
    buttonText: '',
    buttonLink: '',
    footerText: '',
  },
];

export default SYSTEM_EMAIL_DEFAULTS;